name: publish test

on:
  push:
    branches:
    - dev
    - dev-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      run: echo oi
